<p class="headline">
    <? echo T_("Your Files"); ?>
</p>
<p>
    <?php echo T_("You could access these files without any limits."); ?>
</p>
<table width='100%'>
<?
foreach($this->documents as $doc) {
?>
    <tr>
        <td width=400><a href='?fileid=<?php echo $doc["attachmentsid"] ?>&hash=<?=$doc["secure-hash"] ?>'><? echo $doc["name"] ?></a></td>
        <td width=100><? echo $this->filesize($doc["filesize"]) ?></td>
        <td width=100><? echo date("d.m.Y", strtotime($doc["modifiedtime"])) ?></td>
    </tr>
<?
}
?>
</table>
<p>
    <em><?=T_("Every Downloadlink is only valid for 1 hour. Please reload page to get a new link!") ?></em>
</p>
