<p class="loginHead">
    <?=T_("Login for the Customerportal of")." ".COMPANY_NAME ?>
</p>
<div class="login">
    <form method="POST" action="#">
        <p>
            Username
        </p>
        <p>
            <input type="text" name="username" value="">
        </p>
        <p>
            Passwort
        </p>
        <p>
            <input type="password" name="password" value="">
        </p>
        <p>
            <input type="submit" name="submit" value="Login">
        </p>
    </form>
</div>